// Command genprotocolversion generates chain/version/protocol_gen.go from
// the frozen protocol artifact docs/phase-f-freeze.json, so the embedded
// protocol identity is never hand-typed.
//
// Usage (from the chain module directory):
//
//	go run ./tools/genprotocolversion -freeze ../docs/phase-f-freeze.json -out version/protocol_gen.go
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
)

type freezeDoc struct {
	FreezeTag    string `json:"freeze_tag"`
	FreezeCommit string `json:"freeze_tag_commit"`
	Recorded     struct {
		GraphIDV2        string            `json:"graph_id_v2"`
		PolicyID         string            `json:"policy_id"`
		ProtocolVersions map[string]string `json:"protocol_versions"`
	} `json:"recorded"`
}

func main() {
	freezePath := flag.String("freeze", "../docs/phase-f-freeze.json", "path to the freeze artifact")
	outPath := flag.String("out", "version/protocol_gen.go", "output file")
	flag.Parse()

	raw, err := os.ReadFile(*freezePath)
	if err != nil {
		fail("read freeze artifact: %v", err)
	}
	var doc freezeDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		fail("parse freeze artifact: %v", err)
	}
	if doc.FreezeTag == "" || doc.FreezeCommit == "" || doc.Recorded.GraphIDV2 == "" ||
		doc.Recorded.PolicyID == "" || len(doc.Recorded.ProtocolVersions) == 0 {
		fail("freeze artifact is missing required fields")
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by tools/genprotocolversion from %s. DO NOT EDIT.\n\n", *freezePath)
	buf.WriteString("package version\n\n")
	buf.WriteString("const (\n")
	fmt.Fprintf(&buf, "\tFreezeTag = %q\n", doc.FreezeTag)
	fmt.Fprintf(&buf, "\tFreezeCommit = %q\n", doc.FreezeCommit)
	fmt.Fprintf(&buf, "\tGraphIDV2 = %q\n", doc.Recorded.GraphIDV2)
	fmt.Fprintf(&buf, "\tPolicyID = %q\n", doc.Recorded.PolicyID)
	buf.WriteString(")\n\n")
	buf.WriteString("// ProtocolVersions maps frozen protocol component to version, copied verbatim from the freeze artifact.\n")
	buf.WriteString("var ProtocolVersions = map[string]string{\n")
	keys := make([]string, 0, len(doc.Recorded.ProtocolVersions))
	for k := range doc.Recorded.ProtocolVersions {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&buf, "\t%q: %q,\n", k, doc.Recorded.ProtocolVersions[k])
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fail("gofmt generated source: %v", err)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		fail("write %s: %v", *outPath, err)
	}
	fmt.Printf("wrote %s (freeze tag %s, commit %s)\n", *outPath, doc.FreezeTag, doc.FreezeCommit)
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genprotocolversion: "+format+"\n", args...)
	os.Exit(1)
}
