package canonical

// Cross-language vectors: the Go implementation must reproduce
// compute/canonical/testdata/canonical_vectors.json bit-for-bit. The file
// is generated by the independent Python mirror in
// compute/canonical/python/ (canonical_ref.py), which runs the same data
// through its own code; any divergence in math, tensor commitments,
// operator semantics or graph execution fails this test.

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

func loadVectors(t *testing.T) map[string]any {
	t.Helper()
	raw, err := os.ReadFile("testdata/canonical_vectors.json")
	if err != nil {
		t.Fatalf("vectors file: %v", err)
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	var out map[string]any
	if err := dec.Decode(&out); err != nil {
		t.Fatal(err)
	}
	return out
}

func jnum(t *testing.T, v any) int64 {
	t.Helper()
	n, ok := v.(json.Number)
	if !ok {
		t.Fatalf("not a number: %#v", v)
	}
	i, err := n.Int64()
	if err != nil {
		t.Fatalf("not an int64: %v", err)
	}
	return i
}

func jstr(t *testing.T, v any) string {
	t.Helper()
	s, ok := v.(string)
	if !ok {
		t.Fatalf("not a string: %#v", v)
	}
	return s
}

func jarr(t *testing.T, v any) []any {
	t.Helper()
	a, ok := v.([]any)
	if !ok {
		t.Fatalf("not an array: %#v", v)
	}
	return a
}

func jmap(t *testing.T, v any) map[string]any {
	t.Helper()
	m, ok := v.(map[string]any)
	if !ok {
		t.Fatalf("not a map: %#v", v)
	}
	return m
}

func jhex(t *testing.T, v any) []byte {
	t.Helper()
	b, err := hex.DecodeString(jstr(t, v))
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func jdesc(t *testing.T, v any) TensorDescriptor {
	t.Helper()
	m := jmap(t, v)
	shape := []int64{}
	for _, dim := range jarr(t, m["shape"]) {
		shape = append(shape, jnum(t, dim))
	}
	return TensorDescriptor{
		Dtype:  uint8(jnum(t, m["dtype"])),
		Layout: uint8(jnum(t, m["layout"])),
		Shape:  shape,
	}
}

func jdata(t *testing.T, v any) []int32 {
	t.Helper()
	arr := jarr(t, v)
	out := make([]int32, len(arr))
	for i, x := range arr {
		out[i] = int32(jnum(t, x))
	}
	return out
}

func jparams(t *testing.T, v any) ParamList {
	t.Helper()
	var out ParamList
	for _, pairAny := range jarr(t, v) {
		pair := jarr(t, pairAny)
		out = append(out, Pair{Key: jstr(t, pair[0]), Value: jnum(t, pair[1])})
	}
	return out.Canonical()
}

func TestCanonicalCrossLanguageVectors(t *testing.T) {
	vectors := loadVectors(t)
	if got := jstr(t, vectors["math_version"]); got != MathVersion {
		t.Fatalf("math version mismatch: %s", got)
	}

	// --- math primitives ---------------------------------------------------
	mathVectors := jmap(t, vectors["math"])
	for name, casesAny := range mathVectors {
		cases := jarr(t, casesAny)
		if len(cases) == 0 {
			t.Fatalf("no cases for %s", name)
		}
		for i, cAny := range cases {
			c := jarr(t, cAny)
			var got, want int64
			want = jnum(t, c[len(c)-1])
			switch name {
			case "mul_fx":
				got = int64(MulFx(int32(jnum(t, c[0])), int32(jnum(t, c[1]))))
			case "add_fx":
				got = int64(AddFx(int32(jnum(t, c[0])), int32(jnum(t, c[1]))))
			case "sub_fx":
				got = int64(SubFx(int32(jnum(t, c[0])), int32(jnum(t, c[1]))))
			case "div_fx":
				v, err := DivFx(int32(jnum(t, c[0])), int32(jnum(t, c[1])))
				if err != nil {
					t.Fatalf("%s[%d]: %v", name, i, err)
				}
				got = int64(v)
			case "exp_fx":
				got = int64(ExpFx(int32(jnum(t, c[0]))))
			case "sigmoid_fx":
				got = int64(SigmoidFx(int32(jnum(t, c[0]))))
			case "inv_sqrt_fx":
				v, err := InvSqrtFx(jnum(t, c[0]))
				if err != nil {
					t.Fatalf("%s[%d]: %v", name, i, err)
				}
				got = int64(v)
			case "rshift_round_even":
				got = RShiftRoundEven(jnum(t, c[0]), uint(jnum(t, c[1])))
			default:
				t.Fatalf("unknown math vector %s", name)
			}
			if got != want {
				t.Fatalf("%s case %d: got %d, want %d", name, i, got, want)
			}
		}
	}

	// --- tensor roots ------------------------------------------------------
	for _, vAny := range jarr(t, vectors["tensor_roots"]) {
		v := jmap(t, vAny)
		name := jstr(t, v["name"])
		desc := jdesc(t, v["desc"])
		tens := Tensor{Desc: desc, Data: jdata(t, v["data"])}
		root, err := tens.TensorRoot()
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if !bytes.Equal(root[:], jhex(t, v["root"])) {
			t.Fatalf("%s: tensor root mismatch", name)
		}
		merkle, err := tens.MerkleRoot()
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(merkle[:], jhex(t, v["merkle"])) {
			t.Fatalf("%s: merkle root mismatch", name)
		}
	}

	// --- operators ---------------------------------------------------------
	for _, vAny := range jarr(t, vectors["operators"]) {
		v := jmap(t, vAny)
		name := jstr(t, v["name"])
		t.Run("op_"+name, func(t *testing.T) {
			opID := jstr(t, v["operator_id"])
			op, err := Lookup(opID)
			if err != nil {
				t.Fatal(err)
			}
			params := jparams(t, v["params"])
			var ins []Tensor
			var descs []TensorDescriptor
			for _, inAny := range jarr(t, v["inputs"]) {
				in := jmap(t, inAny)
				desc := jdesc(t, in["desc"])
				descs = append(descs, desc)
				ins = append(ins, Tensor{Desc: desc, Data: jdata(t, in["data"])})
			}
			wantDesc := jdesc(t, v["output_desc"])
			specDesc, err := op.OutputSpec(descs, params)
			if err != nil {
				t.Fatal(err)
			}
			if !sameDesc(specDesc, wantDesc) {
				t.Fatalf("output descriptor mismatch: %+v vs %+v", specDesc, wantDesc)
			}
			var out *Tensor
			if opID == OpRoPEFixedV1 {
				hidden := descs[0].Shape[len(descs[0].Shape)-1]
				constants, err := NewRopeConstants(ins[1].Data, int(hidden/2))
				if err != nil {
					t.Fatal(err)
				}
				out, err = ExecuteRope(&ins[0], constants, params)
				if err != nil {
					t.Fatal(err)
				}
			} else {
				out, err = op.Execute(ins, params)
				if err != nil {
					t.Fatal(err)
				}
			}
			wantData := jdata(t, v["output_data"])
			if len(out.Data) != len(wantData) {
				t.Fatalf("output length %d, want %d", len(out.Data), len(wantData))
			}
			for i := range wantData {
				if out.Data[i] != wantData[i] {
					t.Fatalf("output[%d] = %d, want %d", i, out.Data[i], wantData[i])
				}
			}
			root, err := out.TensorRoot()
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(root[:], jhex(t, v["output_root"])) {
				t.Fatal("output tensor root mismatch")
			}
			wantWork := map[string]int64{}
			for _, wAny := range jarr(t, v["work"]) {
				w := jarr(t, wAny)
				wantWork[jstr(t, w[0])] = jnum(t, w[1])
			}
			for key, want := range wantWork {
				if got := op.Work(ins, params).Get(key, -1); got != want {
					t.Fatalf("work %s = %d, want %d", key, got, want)
				}
			}
		})
	}

	// --- graph -------------------------------------------------------------
	gVec := jmap(t, vectors["graph"])
	descMap := jmap(t, gVec["descriptor"])
	graph := &GraphDescriptor{
		ProtocolVersion: jstr(t, descMap["protocol_version"]),
		Spec:            jstr(t, descMap["spec"]),
	}
	for _, inAny := range jarr(t, descMap["inputs"]) {
		in := jmap(t, inAny)
		graph.Inputs = append(graph.Inputs, GraphInput{
			Name: jstr(t, in["name"]),
			Desc: jdesc(t, in["desc"]),
			Root: jhex(t, in["root"]),
		})
	}
	for _, nodeAny := range jarr(t, descMap["nodes"]) {
		n := jmap(t, nodeAny)
		var refs []TensorRef
		for _, refAny := range jarr(t, n["inputs"]) {
			r := jmap(t, refAny)
			refs = append(refs, TensorRef{Kind: uint8(jnum(t, r["kind"])), Index: uint32(jnum(t, r["index"]))})
		}
		graph.Nodes = append(graph.Nodes, GraphNode{
			NodeID:     uint32(jnum(t, n["node_id"])),
			OperatorID: jstr(t, n["operator_id"]),
			Version:    jstr(t, n["operator_version"]),
			Inputs:     refs,
			Output:     jdesc(t, n["output"]),
			Params:     jparams(t, n["params"]),
		})
	}
	for _, refAny := range jarr(t, descMap["outputs"]) {
		r := jmap(t, refAny)
		graph.Outputs = append(graph.Outputs, TensorRef{Kind: uint8(jnum(t, r["kind"])), Index: uint32(jnum(t, r["index"]))})
	}
	graphID, err := graph.GraphID()
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(graphID[:], jhex(t, gVec["graph_id"])) {
		t.Fatal("graph id mismatch")
	}
	inputs := map[uint32]Tensor{}
	for _, inAny := range jarr(t, gVec["inputs"]) {
		in := jmap(t, inAny)
		inputs[uint32(jnum(t, in["index"]))] = Tensor{Desc: jdesc(t, in["desc"]), Data: jdata(t, in["data"])}
	}
	exec, err := ExecuteGraph(graph, inputs, nil)
	if err != nil {
		t.Fatal(err)
	}
	wantTrail := jarr(t, gVec["trail"])
	if len(exec.Trail) != len(wantTrail) {
		t.Fatalf("trail length %d, want %d", len(exec.Trail), len(wantTrail))
	}
	for i, want := range wantTrail {
		if !bytes.Equal(exec.Trail[i][:], jhex(t, want)) {
			t.Fatalf("trail[%d] mismatch", i)
		}
	}
	wantOutputs := jarr(t, gVec["outputs"])
	if len(exec.Outputs) != len(wantOutputs) {
		t.Fatalf("output count %d, want %d", len(exec.Outputs), len(wantOutputs))
	}
	for i, want := range wantOutputs {
		if !bytes.Equal(exec.Outputs[i][:], jhex(t, want)) {
			t.Fatalf("output[%d] root mismatch", i)
		}
	}
	for _, wAny := range jarr(t, gVec["work"]) {
		w := jarr(t, wAny)
		key := jstr(t, w[0])
		if got := exec.WorkVector.Get(key, -1); got != jnum(t, w[1]) {
			t.Fatalf("graph work %s = %d, want %d", key, got, jnum(t, w[1]))
		}
	}
}
