// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: prisma/compute/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryTaskRequest struct {
	TaskId uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (m *QueryTaskRequest) Reset()         { *m = QueryTaskRequest{} }
func (m *QueryTaskRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTaskRequest) ProtoMessage()    {}
func (*QueryTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af1350e5f65f967, []int{0}
}
func (m *QueryTaskRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaskRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaskRequest.Merge(m, src)
}
func (m *QueryTaskRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaskRequest proto.InternalMessageInfo

func (m *QueryTaskRequest) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type QueryTaskResponse struct {
	TaskJson []byte `protobuf:"bytes,1,opt,name=task_json,json=taskJson,proto3" json:"task_json,omitempty"`
}

func (m *QueryTaskResponse) Reset()         { *m = QueryTaskResponse{} }
func (m *QueryTaskResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTaskResponse) ProtoMessage()    {}
func (*QueryTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af1350e5f65f967, []int{1}
}
func (m *QueryTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaskResponse.Merge(m, src)
}
func (m *QueryTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaskResponse proto.InternalMessageInfo

func (m *QueryTaskResponse) GetTaskJson() []byte {
	if m != nil {
		return m.TaskJson
	}
	return nil
}

type QueryModelRequest struct {
	ModelId     string `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	SpecVersion string `protobuf:"bytes,2,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
}

func (m *QueryModelRequest) Reset()         { *m = QueryModelRequest{} }
func (m *QueryModelRequest) String() string { return proto.CompactTextString(m) }
func (*QueryModelRequest) ProtoMessage()    {}
func (*QueryModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af1350e5f65f967, []int{2}
}
func (m *QueryModelRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryModelRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModelRequest.Merge(m, src)
}
func (m *QueryModelRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModelRequest proto.InternalMessageInfo

func (m *QueryModelRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *QueryModelRequest) GetSpecVersion() string {
	if m != nil {
		return m.SpecVersion
	}
	return ""
}

type QueryModelResponse struct {
	ModelJson []byte `protobuf:"bytes,1,opt,name=model_json,json=modelJson,proto3" json:"model_json,omitempty"`
}

func (m *QueryModelResponse) Reset()         { *m = QueryModelResponse{} }
func (m *QueryModelResponse) String() string { return proto.CompactTextString(m) }
func (*QueryModelResponse) ProtoMessage()    {}
func (*QueryModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af1350e5f65f967, []int{3}
}
func (m *QueryModelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryModelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModelResponse.Merge(m, src)
}
func (m *QueryModelResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModelResponse proto.InternalMessageInfo

func (m *QueryModelResponse) GetModelJson() []byte {
	if m != nil {
		return m.ModelJson
	}
	return nil
}

type QueryWorkerRequest struct {
	Worker string `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
}

func (m *QueryWorkerRequest) Reset()         { *m = QueryWorkerRequest{} }
func (m *QueryWorkerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWorkerRequest) ProtoMessage()    {}
func (*QueryWorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af1350e5f65f967, []int{4}
}
func (m *QueryWorkerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWorkerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWorkerRequest.Merge(m, src)
}
func (m *QueryWorkerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWorkerRequest proto.InternalMessageInfo

func (m *QueryWorkerRequest) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

type QueryWorkerResponse struct {
	BondedUprsm      uint64 `protobuf:"varint,1,opt,name=bonded_uprsm,json=bondedUprsm,proto3" json:"bonded_uprsm,omitempty"`
	NetworkPublicKey []byte `protobuf:"bytes,2,opt,name=network_public_key,json=networkPublicKey,proto3" json:"network_public_key,omitempty"`
	ReservedUprsm    uint64 `protobuf:"varint,3,opt,name=reserved_uprsm,json=reservedUprsm,proto3" json:"reserved_uprsm,omitempty"`
}

func (m *QueryWorkerResponse) Reset()         { *m = QueryWorkerResponse{} }
func (m *QueryWorkerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWorkerResponse) ProtoMessage()    {}
func (*QueryWorkerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af1350e5f65f967, []int{5}
}
func (m *QueryWorkerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWorkerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWorkerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWorkerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWorkerResponse.Merge(m, src)
}
func (m *QueryWorkerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWorkerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWorkerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWorkerResponse proto.InternalMessageInfo

func (m *QueryWorkerResponse) GetBondedUprsm() uint64 {
	if m != nil {
		return m.BondedUprsm
	}
	return 0
}

func (m *QueryWorkerResponse) GetNetworkPublicKey() []byte {
	if m != nil {
		return m.NetworkPublicKey
	}
	return nil
}

func (m *QueryWorkerResponse) GetReservedUprsm() uint64 {
	if m != nil {
		return m.ReservedUprsm
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryTaskRequest)(nil), "prisma.compute.v1.QueryTaskRequest")
	proto.RegisterType((*QueryTaskResponse)(nil), "prisma.compute.v1.QueryTaskResponse")
	proto.RegisterType((*QueryModelRequest)(nil), "prisma.compute.v1.QueryModelRequest")
	proto.RegisterType((*QueryModelResponse)(nil), "prisma.compute.v1.QueryModelResponse")
	proto.RegisterType((*QueryWorkerRequest)(nil), "prisma.compute.v1.QueryWorkerRequest")
	proto.RegisterType((*QueryWorkerResponse)(nil), "prisma.compute.v1.QueryWorkerResponse")
}

func init() { proto.RegisterFile("prisma/compute/v1/query.proto", fileDescriptor_3af1350e5f65f967) }

var fileDescriptor_3af1350e5f65f967 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcf, 0x6b, 0xd4, 0x40,
	0x14, 0xde, 0xd4, 0x36, 0xed, 0xbe, 0x46, 0x69, 0x47, 0xd0, 0xba, 0xd2, 0xe0, 0x46, 0x2b, 0x82,
	0x25, 0xb1, 0xf6, 0xe8, 0xcd, 0x5b, 0x15, 0xc1, 0x0d, 0xd5, 0x82, 0x97, 0x90, 0x4d, 0x1e, 0x18,
	0xd3, 0x64, 0xa6, 0x33, 0x49, 0x34, 0x7f, 0x82, 0x07, 0xc1, 0x3f, 0xcb, 0x63, 0x8f, 0x1e, 0x65,
	0xf7, 0x1f, 0x91, 0xf9, 0x91, 0x25, 0xab, 0x6c, 0xf7, 0x32, 0xf0, 0xbe, 0xef, 0x7b, 0xdf, 0x7c,
	0xf3, 0x1e, 0x03, 0x87, 0x8c, 0x67, 0xa2, 0x88, 0x83, 0x84, 0x16, 0xac, 0xae, 0x30, 0x68, 0x4e,
	0x82, 0xab, 0x1a, 0x79, 0xeb, 0x33, 0x4e, 0x2b, 0x4a, 0xf6, 0x35, 0xed, 0x1b, 0xda, 0x6f, 0x4e,
	0xbc, 0xe7, 0xb0, 0x37, 0x91, 0x8a, 0xf3, 0x58, 0xe4, 0x21, 0x5e, 0xd5, 0x28, 0x2a, 0x72, 0x1f,
	0xb6, 0xab, 0x58, 0xe4, 0x51, 0x96, 0x1e, 0x58, 0x8f, 0xac, 0x67, 0x9b, 0xa1, 0x2d, 0xcb, 0xb3,
	0xd4, 0x7b, 0x01, 0xfb, 0x3d, 0xb1, 0x60, 0xb4, 0x14, 0x48, 0x1e, 0xc2, 0x50, 0xa9, 0xbf, 0x08,
	0x5a, 0x2a, 0xbd, 0x13, 0xee, 0x48, 0xe0, 0x8d, 0xa0, 0xa5, 0x37, 0x31, 0x1d, 0xef, 0x68, 0x8a,
	0x97, 0x9d, 0xff, 0x03, 0xd8, 0x29, 0x64, 0xdd, 0x5d, 0x30, 0x0c, 0xb7, 0x55, 0x7d, 0x96, 0x92,
	0x31, 0x38, 0x82, 0x61, 0x12, 0x35, 0xc8, 0x45, 0x46, 0xcb, 0x83, 0x0d, 0x45, 0xef, 0x4a, 0xec,
	0xa3, 0x86, 0xbc, 0x53, 0x20, 0x7d, 0x4b, 0x93, 0xe2, 0x10, 0x40, 0x7b, 0xf6, 0x62, 0x0c, 0x15,
	0xa2, 0x72, 0x1c, 0x9b, 0xa6, 0x0b, 0xca, 0x73, 0xe4, 0x5d, 0x90, 0x7b, 0x60, 0x7f, 0x55, 0x80,
	0x89, 0x61, 0x2a, 0xef, 0x87, 0x05, 0x77, 0x97, 0xe4, 0xe6, 0x92, 0x31, 0x38, 0x53, 0x5a, 0xa6,
	0x98, 0x46, 0x35, 0xe3, 0xa2, 0x30, 0xd3, 0xd9, 0xd5, 0xd8, 0x07, 0x09, 0x91, 0x63, 0x20, 0x25,
	0x56, 0xd2, 0x27, 0x62, 0xf5, 0xf4, 0x32, 0x4b, 0xa2, 0x1c, 0x5b, 0xf5, 0x0c, 0x27, 0xdc, 0x33,
	0xcc, 0x7b, 0x45, 0xbc, 0xc5, 0x96, 0x1c, 0xc1, 0x1d, 0x8e, 0x02, 0x79, 0xb3, 0xb0, 0xbc, 0xa5,
	0x2c, 0x6f, 0x77, 0xa8, 0x32, 0x7d, 0xf9, 0x7d, 0x03, 0xb6, 0x54, 0x1e, 0x32, 0x81, 0x4d, 0x39,
	0x7c, 0xf2, 0xd8, 0xff, 0x6f, 0x95, 0xfe, 0xbf, 0x7b, 0x1c, 0x3d, 0xb9, 0x59, 0x64, 0x1e, 0x75,
	0x0e, 0x5b, 0x6a, 0x94, 0x64, 0xa5, 0xbc, 0xbf, 0xbc, 0xd1, 0xd1, 0x1a, 0x95, 0x71, 0xbd, 0x00,
	0x5b, 0x0f, 0x8f, 0xac, 0x6c, 0x58, 0xda, 0xc5, 0xe8, 0xe9, 0x3a, 0x99, 0x36, 0x7e, 0xfd, 0xea,
	0xd7, 0xcc, 0xb5, 0xae, 0x67, 0xae, 0xf5, 0x67, 0xe6, 0x5a, 0x3f, 0xe7, 0xee, 0xe0, 0x7a, 0xee,
	0x0e, 0x7e, 0xcf, 0xdd, 0xc1, 0xa7, 0xb1, 0x36, 0x48, 0x3e, 0xc7, 0x59, 0x19, 0xe8, 0xf3, 0xdb,
	0xe2, 0x27, 0x54, 0x2d, 0x43, 0x31, 0xb5, 0xd5, 0x3f, 0x38, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0x64, 0xb5, 0xc6, 0x28, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Task(ctx context.Context, in *QueryTaskRequest, opts ...grpc.CallOption) (*QueryTaskResponse, error)
	Model(ctx context.Context, in *QueryModelRequest, opts ...grpc.CallOption) (*QueryModelResponse, error)
	Worker(ctx context.Context, in *QueryWorkerRequest, opts ...grpc.CallOption) (*QueryWorkerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Task(ctx context.Context, in *QueryTaskRequest, opts ...grpc.CallOption) (*QueryTaskResponse, error) {
	out := new(QueryTaskResponse)
	err := c.cc.Invoke(ctx, "/prisma.compute.v1.Query/Task", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Model(ctx context.Context, in *QueryModelRequest, opts ...grpc.CallOption) (*QueryModelResponse, error) {
	out := new(QueryModelResponse)
	err := c.cc.Invoke(ctx, "/prisma.compute.v1.Query/Model", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Worker(ctx context.Context, in *QueryWorkerRequest, opts ...grpc.CallOption) (*QueryWorkerResponse, error) {
	out := new(QueryWorkerResponse)
	err := c.cc.Invoke(ctx, "/prisma.compute.v1.Query/Worker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Task(context.Context, *QueryTaskRequest) (*QueryTaskResponse, error)
	Model(context.Context, *QueryModelRequest) (*QueryModelResponse, error)
	Worker(context.Context, *QueryWorkerRequest) (*QueryWorkerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Task(ctx context.Context, req *QueryTaskRequest) (*QueryTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Task not implemented")
}
func (*UnimplementedQueryServer) Model(ctx context.Context, req *QueryModelRequest) (*QueryModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Model not implemented")
}
func (*UnimplementedQueryServer) Worker(ctx context.Context, req *QueryWorkerRequest) (*QueryWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Worker not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Task_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Task(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prisma.compute.v1.Query/Task",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Task(ctx, req.(*QueryTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Model_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Model(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prisma.compute.v1.Query/Model",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Model(ctx, req.(*QueryModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Worker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Worker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prisma.compute.v1.Query/Worker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Worker(ctx, req.(*QueryWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prisma.compute.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Task",
			Handler:    _Query_Task_Handler,
		},
		{
			MethodName: "Model",
			Handler:    _Query_Model_Handler,
		},
		{
			MethodName: "Worker",
			Handler:    _Query_Worker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prisma/compute/v1/query.proto",
}

func (m *QueryTaskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaskRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TaskId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TaskJson) > 0 {
		i -= len(m.TaskJson)
		copy(dAtA[i:], m.TaskJson)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TaskJson)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryModelRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryModelRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryModelRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SpecVersion) > 0 {
		i -= len(m.SpecVersion)
		copy(dAtA[i:], m.SpecVersion)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SpecVersion)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModelId) > 0 {
		i -= len(m.ModelId)
		copy(dAtA[i:], m.ModelId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ModelId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryModelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryModelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryModelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ModelJson) > 0 {
		i -= len(m.ModelJson)
		copy(dAtA[i:], m.ModelJson)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ModelJson)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWorkerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWorkerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWorkerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Worker) > 0 {
		i -= len(m.Worker)
		copy(dAtA[i:], m.Worker)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Worker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWorkerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWorkerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWorkerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReservedUprsm != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ReservedUprsm))
		i--
		dAtA[i] = 0x18
	}
	if len(m.NetworkPublicKey) > 0 {
		i -= len(m.NetworkPublicKey)
		copy(dAtA[i:], m.NetworkPublicKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NetworkPublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if m.BondedUprsm != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BondedUprsm))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTaskRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskId != 0 {
		n += 1 + sovQuery(uint64(m.TaskId))
	}
	return n
}

func (m *QueryTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskJson)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryModelRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModelId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SpecVersion)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryModelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModelJson)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWorkerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Worker)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWorkerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BondedUprsm != 0 {
		n += 1 + sovQuery(uint64(m.BondedUprsm))
	}
	l = len(m.NetworkPublicKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ReservedUprsm != 0 {
		n += 1 + sovQuery(uint64(m.ReservedUprsm))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTaskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskJson", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskJson = append(m.TaskJson[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskJson == nil {
				m.TaskJson = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryModelRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryModelRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryModelRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpecVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpecVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryModelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryModelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryModelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelJson", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelJson = append(m.ModelJson[:0], dAtA[iNdEx:postIndex]...)
			if m.ModelJson == nil {
				m.ModelJson = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWorkerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWorkerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWorkerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Worker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWorkerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWorkerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWorkerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondedUprsm", wireType)
			}
			m.BondedUprsm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondedUprsm |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkPublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkPublicKey = append(m.NetworkPublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.NetworkPublicKey == nil {
				m.NetworkPublicKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedUprsm", wireType)
			}
			m.ReservedUprsm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReservedUprsm |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
