// Code generated by tools/genprotocolversion from ../docs/phase-f-freeze.json. DO NOT EDIT.

package version

const (
	FreezeTag    = "transformer-phase-f-wide-integer"
	FreezeCommit = "89547fa97b62d72a4cd336a5dfd3b000b03eac60"
	GraphIDV2    = "8fb86087697e277602bb4b2088ba48eb4172c21d9c4f83914582f2cbf00d4def"
	PolicyID     = "eb9a9fef403c95cd0ab876893acf14e02928245306f1d1cc6e12f4d99c5eb7a0"
)

// ProtocolVersions maps frozen protocol component to version, copied verbatim from the freeze artifact.
var ProtocolVersions = map[string]string{
	"bundle_v2":            "GRAPH_VERIFICATION_BUNDLE_V2/1.0.0",
	"commit_v3":            "3.0.0",
	"freivalds_wide":       "FREIVALDS_A13W10_I64_V1/1.0.0",
	"gemm_wide":            "GEMM_A13W10_I64_V1/1.0.0",
	"graph_da_attestation": "GRAPH_DA_ATTESTATION_V2/1.0.0",
	"graph_v2":             "CANONICAL_GRAPH_V2/1.0.0",
	"receipt_v3":           "3.0.0",
	"requant_wide":         "REQUANTIZE_WIDE_V1/1.0.0",
	"tensor_v2":            "CANONICAL_TENSOR_V2/1.0.0",
}
