package verify

// Test H of v0.1.2: cross-language Freivalds vectors. The Go implementation
// must reproduce compute/gemmv1/testdata/freivalds_vectors.json exactly;
// the file is generated by the independent Python implementation, which
// runs the same check against its own code.

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"

	"prismachain/compute/gemmv1"
)

func TestCrossLanguageFreivaldsVectors(t *testing.T) {
	raw, err := os.ReadFile("../testdata/freivalds_vectors.json")
	if err != nil {
		t.Fatalf("vectors file: %v", err)
	}
	var vectors struct {
		Cases []struct {
			Name         string  `json:"name"`
			M, N, K      uint64  `json:"-"`
			RawM         float64 `json:"m"`
			RawN         float64 `json:"n"`
			RawK         float64 `json:"k"`
			Seed         float64 `json:"seed"`
			RSeed        float64 `json:"r_seed"`
			Rounds       float64 `json:"rounds"`
			MatrixA      string  `json:"matrix_a"`
			MatrixB      string  `json:"matrix_b"`
			CHonest      string  `json:"c_honest"`
			CFraud       string  `json:"c_fraud"`
			RoundsDetail []struct {
				Round        int      `json:"round"`
				R            string   `json:"r"`
				X            string   `json:"x"`
				Y            string   `json:"y"`
				Z            string   `json:"z"`
				ResidualRows []uint64 `json:"residual_rows"`
			} `json:"rounds_detail"`
			DetectedAt *int     `json:"fraud_detected_at_round"`
			Residual   []uint64 `json:"residual_rows"`
			Loc        *struct {
				Row     int   `json:"row"`
				BadCols []int `json:"bad_cols"`
				TileI   int   `json:"tile_i"`
				TileJ   int   `json:"tile_j"`
			} `json:"localization"`
		} `json:"cases"`
	}
	if err := json.Unmarshal(raw, &vectors); err != nil {
		t.Fatal(err)
	}
	for _, c := range vectors.Cases {
		t.Run(c.Name, func(t *testing.T) {
			m, n, k := uint64(c.RawM), uint64(c.RawN), uint64(c.RawK)
			seed := uint32(c.Seed)
			a := gemmv1.GenTestMatrix('A', seed, m*k)
			b := gemmv1.GenTestMatrix('B', seed, k*n)
			if hex.EncodeToString(gemmv1.Int8ToBytes(a)) != c.MatrixA {
				t.Fatal("matrix A does not match the vector")
			}
			if hex.EncodeToString(gemmv1.Int8ToBytes(b)) != c.MatrixB {
				t.Fatal("matrix B does not match the vector")
			}
			cHonest := gemmv1.ReferenceGEMM(a, b, m, n, k)
			if hex.EncodeToString(gemmv1.Int32sToCanonical(cHonest)) != c.CHonest {
				t.Fatal("honest C does not match the vector")
			}
			if hex.EncodeToString(gemmv1.Int32sToCanonical(mustFraudC(t, cHonest, m, n))) != c.CFraud {
				t.Fatal("fraud C does not match the vector")
			}
			fraudVals, err := gemmv1.CanonicalToInt32s(mustBytes(t, c.CFraud))
			if err != nil {
				t.Fatal(err)
			}

			src := NewDeterministicSource([]byte{byte(c.RSeed)})
			for _, rd := range c.RoundsDetail {
				r := RandomBinaryVector(src, n)
				if hex.EncodeToString(r) != rd.R {
					t.Fatalf("round %d: r stream mismatch", rd.Round)
				}
				x, y, z := FreivaldsRound(a, b, fraudVals, m, n, k, r)
				assertHexI64(t, "x", x, rd.X)
				assertHexI64(t, "y", y, rd.Y)
				assertHexI64(t, "z", z, rd.Z)
				if !equalU64(ResidualBadRows(y, z), rd.ResidualRows) {
					t.Fatalf("round %d: residual rows mismatch", rd.Round)
				}
			}
			if c.DetectedAt == nil {
				t.Fatal("vector fraud was not detected by the python stream")
			}
			loc, found, err := LocalizeFromRows(a, b, fraudVals, m, n, k, c.Residual)
			if err != nil || !found {
				t.Fatalf("localization failed: found=%v err=%v", found, err)
			}
			if int(loc.Row) != c.Loc.Row || loc.TileI != uint64(c.Loc.TileI) || loc.TileJ != uint64(c.Loc.TileJ) {
				t.Fatalf("localization mismatch: got row %d tile (%d,%d)", loc.Row, loc.TileI, loc.TileJ)
			}
		})
	}
}

func mustFraudC(t *testing.T, c []int32, m, n uint64) []int32 {
	t.Helper()
	out := append([]int32(nil), c...)
	out[5*n+9]++
	return out
}

func mustBytes(t *testing.T, h string) []byte {
	t.Helper()
	b, err := hex.DecodeString(h)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func assertHexI64(t *testing.T, field string, vals []int64, wantHex string) {
	t.Helper()
	want, err := hex.DecodeString(wantHex)
	if err != nil {
		t.Fatalf("%s: bad hex: %v", field, err)
	}
	var got []byte
	for _, v := range vals {
		got = binary.BigEndian.AppendUint64(got, uint64(v))
	}
	_ = got
	if !bytes.Equal(got, want) {
		t.Fatalf("%s: Go does not match the Python vectors", field)
	}
}
