package gemmv1

// Test J: cross-language vectors. The Go implementation must reproduce
// compute/gemmv1/testdata/cross_language_vectors.json bit-for-bit; the file
// is generated by the independent Python implementation in
// compute/gemmv1/python/gemmv1/gen_vectors.py, which runs the same check
// against its own code.

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

func TestCrossLanguageVectors(t *testing.T) {
	raw, err := os.ReadFile("testdata/cross_language_vectors.json")
	if err != nil {
		t.Fatalf("vectors file: %v", err)
	}
	var plain map[string]any
	if err := json.Unmarshal(raw, &plain); err != nil {
		t.Fatal(err)
	}
	cases, ok := plain["cases"].([]any)
	if !ok || len(cases) == 0 {
		t.Fatal("no vector cases")
	}
	for _, cAny := range cases {
		c, ok := cAny.(map[string]any)
		if !ok {
			t.Fatal("bad case shape")
		}
		name := c["name"].(string)
		t.Run(name, func(t *testing.T) {
			m := uint64(c["m"].(float64))
			n := uint64(c["n"].(float64))
			k := uint64(c["k"].(float64))
			seed := uint32(c["seed"].(float64))

			matrixA := GenTestMatrix('A', seed, m*k)
			matrixB := GenTestMatrix('B', seed, k*n)
			rootA, rootB, err := BuildMatrixRoots(matrixA, matrixB, m, n, k)
			if err != nil {
				t.Fatal(err)
			}
			assertHex(t, "matrix_a_root", rootA[:], c["matrix_a_root"].(string))
			assertHex(t, "matrix_b_root", rootB[:], c["matrix_b_root"].(string))

			task := &TaskDescriptor{
				ProtocolVersion: ProtocolVersion,
				Operator:        Operator,
				RequesterPubKey: Int8ToBytes(GenTestMatrix('Q', seed, 32)),
				RequesterNonce:  Int8ToBytes(GenTestMatrix('N', seed, 16)),
				IssuedEpoch:     1000,
				M:               m,
				N:               n,
				K:               k,
				MatrixARoot:     rootA[:],
				MatrixBRoot:     rootB[:],
				ArithmeticSpec:  ArithmeticSpec,
				TileSize:        TileSize,
				ChallengeWindow: 100,
				MaxPricePerCWU:  1000,
				SettlementAsset: SettlementAssetUPRSM,
			}
			taskID, err := task.TaskID()
			if err != nil {
				t.Fatal(err)
			}
			assertHex(t, "task_id", taskID, c["task_id"].(string))

			assignment := &Assignment{
				TaskID:          taskID,
				WorkerPubKey:    Int8ToBytes(GenTestMatrix('W', seed, 32)),
				AssignmentNonce: Int8ToBytes(GenTestMatrix('M', seed, 16)),
				AcceptedEpoch:   1001,
			}
			assignmentID, err := assignment.AssignmentID()
			if err != nil {
				t.Fatal(err)
			}
			assertHex(t, "assignment_id", assignmentID, c["assignment_id"].(string))

			cvals := ReferenceGEMM(matrixA, matrixB, m, n, k)
			tiles := OutputTiles(cvals, m, n)
			colsC := uint32(tileCols(n))
			leaves := OutputLeaves(taskID, assignmentID, tiles, colsC)
			outputRoot, err := MerkleRoot(leaves)
			if err != nil {
				t.Fatal(err)
			}
			assertHex(t, "output_root", outputRoot[:], c["output_root"].(string))

			receipt := &VerifiedWorkReceipt{
				ProtocolVersion:   ProtocolVersion,
				TaskID:            taskID,
				AssignmentID:      assignmentID,
				WorkerPubKey:      assignment.WorkerPubKey,
				Operator:          Operator,
				CanonicalMACCount: m * n * k,
				OutputRoot:        outputRoot[:],
				VerificationMode:  ModeOptimisticUnchallenged,
				FinalizedEpoch:    2000,
			}
			receiptID, err := receipt.ReceiptID()
			if err != nil {
				t.Fatal(err)
			}
			assertHex(t, "receipt_id", receiptID, c["receipt_id"].(string))

			taskCBOR, err := EncodeCanonical(task)
			if err != nil {
				t.Fatal(err)
			}
			assertHex(t, "canonical_task_cbor", taskCBOR, c["canonical_task_cbor"].(string))
			receiptCBOR, err := EncodeCanonical(receipt)
			if err != nil {
				t.Fatal(err)
			}
			assertHex(t, "canonical_receipt_cbor", receiptCBOR, c["canonical_receipt_cbor"].(string))
		})
	}
}

func assertHex(t *testing.T, field string, got []byte, wantHex string) {
	t.Helper()
	want, err := hex.DecodeString(wantHex)
	if err != nil {
		t.Fatalf("%s: bad hex in vectors: %v", field, err)
	}
	if !equalBytes(got, want) {
		t.Fatalf("%s: got %x, want %x (Go does not match the Python vectors)", field, got, want)
	}
}
